---
name: Check install

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4
      - name: Install plugin
        run: |-
          helm plugin install https://github.com/nhomble/helm-contains
